baseurl = "https://technocrat.rbind.io/"
languageCode = "en-us"
title = "Locus: Richard Careaga"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true
baseURL = "https://technocrat.rbind.io/"
[outputs]
    #home = [ "HTML", "CSS", "RSS" ]
    home = [ "HTML", "CSS"]
    section = [ "HTML", "RSS" ]

[permalinks]
    post = "/:year/:month/:day/:slug/"


[[menu.main]]
    name = "GitHub"
    url = "https://github.com/technocrat"
    weight = 2

[[menu.main]]
    name = "Portfolio"
    url = "https://technocrat.github.io/_book/"
    weight = 3

[[menu.main]]

    name = "Quotes"
    url = "/quotes/"
    weight = 4

[[menu.main]]

    name = "LinkedIn"
    url = "https://linkedin.com/in/richardcareaga"
    weight = 5

[[menu.main]]

    name = "Twitter"
    url = "https://twitter.com/technocrat"
    weight = 6

[[menu.main]]

    name = "Employment"
    url = "/employment/"
    weight = 7

[[menu.main]]

    name = "RStudio Community"
    url = "https://community.rstudio.com/u/technocrat/activity"
    weight = 8

[params]
    description = "A website built through Hugo and blogdown."
    customCSS = ["css/custom.css"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
